// Faculty and Academic Staff Data - Official Roster (Updated & Verified)
window.facultyData = [
    {
        id: "dr-ehssan-hamdan",
        nameAr: "د. إحسان حمدان حمدان",
        titleAr: "دكتور",
        roleAr: "رئيس الجامعة العالمية للطب الشمولي",
        roleEn: "University President & Founder",
        specializationAr: "فقه الطب الشمولي وعلم المسارات المقارن",
        specializationEn: "Holistic Medicine Jurisprudence & Comparative Neural Pathways",
        category: "neuro",
        photo: "Albums/University_Assets/dr-ehssan-hamdan.jpg",
        cvFile: "docs/faculty_cvs/cv_dr_ehssan_hamdan.md",
        initials: "إ.ح",
        status: "رئيس الجامعة",
        badgeType: "leadership",
        location: "دمشق، سوريا",
        email: "dr.ehssanhamdan@gmail.com",
        phone: null,
        credentials: [
            "شهادة معتمدة – جامعة أكسفورد، بريطانيا",
            "شهادة نقابة المهن الطبية – الأردن (رقم العضوية 7966) باختصاص طب التدليك العلاجي",
            "مستشار ومدرب دولي معتمد (DSC) في مهارات وفقه الطب الشمولي",
            "مؤسس المنظمة الدولية للطب الشمولي (IHMO)",
            "مؤسس الموسوعة العلمية في فقه طب الأعشاب المقارن",
            "مؤسس قاعة البحث العلمي والدراسات العليا في الطب الشمولي"
        ],
        summaryAr: "رئيس الجامعة العالمية الافتراضية للطب الشمولي والعلوم التطبيقية ومؤسس المنظمة الدولية للطب الشمولي (IHMO). مبتكر منهج فقه الطب الشمولي وعلم المسارات المقارن، وخبير رائد في تشخيص جذر العلة وإدارة الأمراض المناعية والعلاج التكاملي."
    },
    {
        id: "dr-abdulwahab-alqahtani",
        nameAr: "د. عبد الوهاب القحطاني",
        fullNameAr: "د. عبد الوهاب القحطاني (عبد الوهاب رزوقي خماس)",
        titleAr: "دكتور",
        roleAr: "نائب رئيس الجامعة",
        roleEn: "Vice President & Academic Specialist",
        specializationAr: "العلاج اليدوي وتقويم العمود الفقري والطب الشمولي",
        specializationEn: "Manual Therapy, Chiropractic & Holistic Medicine",
        category: "chiropractic",
        photo: "Albums/University_Assets/dr-abdulwahab-alqahtani.jpg",
        cvFile: "docs/faculty_cvs/cv_dr_abdulwahab_alqahtani.md",
        initials: "ع.ق",
        status: "نائب الرئيس",
        badgeType: "leadership",
        location: "أربيل، العراق",
        phone: "+9647734224220",
        email: null,
        credentials: [
            "دكتوراه فخرية في علم الحجامة – جامعة سمارت الدولية",
            "بورد TBEPMPT معتمد في علم العقاقير والعلاج بالنباتات – CPD UK (#781861) بالأبوستيل البريطاني (2024م)",
            "دبلوم الطب التجميلي التكاملي – أكاديمية الرؤية الدولية، المملكة المتحدة (300 ساعة - 2025م)",
            "دبلوم العلوم الصيدلانية ومستحضرات التجميل الطبيعية – بالتعاون مع التعليم الفني والمهني",
            "دبلوم الإبر الصينية والعلاج بالضغط – الأكاديمية المصرية الصينية للطب البديل",
            "أخصائي معتمد – منظمة الصحة الدولية للأعشاب",
            "عضو: نقابة الطب التكميلي العراقية، نقابة العشابين الكردستانية، ومنظمة الطب التكاملي الماليزية"
        ],
        summaryAr: "أخصائي ممارس وباحث في الطب الشمولي والطب التكاملي والحجامة المتقدمة والإبر الصينية والعلق الطبي والتأهيل البدني. نائب رئيس الجامعة وعضو مؤسس لمشروع ألف معالج في الطب الشمولي."
    },
    {
        id: "dr-leila-sekkak",
        nameAr: "د. ليلى سكاك",
        titleAr: "دكتورة",
        roleAr: "الوكيل العلمي للجامعة",
        roleEn: "Scientific Vice President & Academic Dean",
        specializationAr: "علم المسارات العصبية والتغذية العلاجية",
        specializationEn: "Neuroscience & Neural Pathways | Clinical Nutrition",
        category: "neuro",
        photo: "Albums/University_Assets/dr-leila-sekkak.jpg",
        cvFile: "docs/faculty_cvs/cv_leila_sakkak.md",
        initials: "ل.س",
        status: "الوكيل العلمي",
        badgeType: "leadership",
        location: "الجزائر",
        email: "trainerleila26@gmail.com",
        phone: "+213664083947",
        telegram: "https://t.me/profleila",
        credentials: [
            "ماجستير في التغذية العلاجية – الجامعة العالمية للطب الشمولي",
            "بكالوريوس في الطب الشمولي",
            "دبلوم عالٍ في علم المسارات العصبية – الجامعة العالمية الافتراضية",
            "مدرب دولي معتمد (تخصص علم المسارات العصبية) – جامعة أكسفورد",
            "محاضرة معتمدة في منصة Udemy والأكاديمية الدولية للتطوير البشري",
            "خبرة +10 سنوات في التغذية العلاجية والمسارات والطب الشمولي"
        ],
        summaryAr: "الوكيل العلمي للجامعة العالمية الافتراضية. تمتلك خبرة تفوق 10 سنوات في التغذية العلاجية المتقدمة وعلم المسارات العصبية، ومحاضرة معتمدة دولياً ومؤلفة للعديد من البرامج التدريبية المرموقة."
    },
    {
        id: "mukhtar-mani",
        nameAr: "مختار محمد أحمد مانع",
        titleAr: "أستاذ",
        roleAr: "أستاذ أكاديمي وطبيب أعشاب",
        roleEn: "Academic Lecturer & Herbal Medicine Practitioner",
        specializationAr: "علم الأعشاب المهنية وكيمياء النباتات الطبية",
        specializationEn: "Professional Herbal Science & Medicinal Phytochemistry",
        category: "herbal",
        photo: "Albums/University_Assets/mukhtar-mani.jpg",
        cvFile: "docs/faculty_cvs/cv_mukhtar_mani.md",
        initials: "م.م",
        status: "معتمد رسمياً",
        badgeType: "certified",
        location: "تعز، اليمن",
        credentials: [
            "بكالوريوس – أكاديمية فيجن الدولية البريطانية، فرع اليمن (2025م)",
            "دبلوم علم العقاقير وكيمياء النباتات الطبية – جامعة تعز (2022م)",
            "دبلوم الطب التجميلي الطبيعي – وزارة الصحة العامة والسكان (2024م)",
            "دبلوم التغذية والطب النبوي – فيجن الدولية البريطانية (2024م)",
            "أكثر من 17 شهادة تخصصية معتمدة من منظمة الصحة العالمية (WHO)",
            "مدير العلاقات العامة والإعلام – نقابة مهن الأعشاب العلمية في اليمن"
        ],
        summaryAr: "أستاذ أكاديمي وطبيب أعشاب وراقٍ وخطيب. يجمع بين الخبرة الأكاديمية والتربوية العريقة والتخصص الدقيق في كيمياء النباتات الطبية وعلم العقاقير، ومسؤول العلاقات العامة بنقابة الأعشاب العلمية."
    },
    {
        id: "habib-jilani",
        nameAr: "حبيب محمد جيلاني",
        titleAr: "أستاذ",
        roleAr: "خبير أعشاب ومعلم قرآن كريم",
        roleEn: "Herbal Science Expert & Academic Instructor",
        specializationAr: "علم الأعشاب المهنية والرقية الشرعية",
        specializationEn: "Professional Herbal Science & Prophetic Medicine",
        category: "herbal",
        photo: "Albums/University_Assets/habib-jilani.jpg",
        cvFile: "docs/faculty_cvs/cv_habib_jilani.md",
        initials: "ح.ج",
        status: "معتمد رسمياً",
        badgeType: "certified",
        location: "المدينة المنورة، المملكة العربية السعودية",
        email: "Nabib65@gmail.com",
        phone: "+966509634974",
        credentials: [
            "بكالوريوس شريعة إسلامية",
            "طالب ماجستير في علوم الطب الإسلامي – الجامعة العالمية الافتراضية",
            "دبلوم الرقية الشرعية – معهد النور",
            "إجازة علمية في كتاب (كنز الثمين من الطب الإغريقي القديم)",
            "خبرة تفوق 15 عاماً كمعلم قرآن ومعالج معتمد بالأعشاب الطبيعية"
        ],
        summaryAr: "خبير أعشاب وباحث شرعي ومعلم قرآن كريم بخبرة تتجاوز 15 عاماً بالمدينة المنورة. يحمل إجازات علمية رصينة في الطب التراثي والإغريقي القديم والرقية والعلوم الشرعية."
    },
    {
        id: "najeeb-sinan",
        nameAr: "نجيب أحمد عبده سنان",
        titleAr: "أستاذ",
        roleAr: "طبيب أعشاب ومدرب تغذية علاجية",
        roleEn: "Herbal Medicine Practitioner & Nutrition Coach",
        specializationAr: "مدرب تغذية مهنية وعلم العقاقير النباتية",
        specializationEn: "Professional Nutrition Coach & Pharmacognosy",
        category: "nutrition",
        photo: "Albums/University_Assets/najeeb-sinan.jpg",
        cvFile: "docs/faculty_cvs/cv_najeeb_sinan.md",
        initials: "ن.س",
        status: "معتمد رسمياً",
        badgeType: "certified",
        location: "تعز، اليمن",
        email: "Najeebsenan43@gmail.com",
        phone: "+967771272778",
        credentials: [
            "دبلوم عالٍ في علم العقاقير والطب النباتي والبديل – أكاديمية فيجن الدولية (2024م)",
            "بكالوريوس كيمياء وأحياء – كلية التربية، جامعة تعز (1995م)",
            "عضو المركز العالمي لأبحاث النباتات الطبية",
            "عضو نقابة العاملين بالأعشاب الطبيعية (المدير المالي للنقابة)",
            "خبرة تفوق 10 سنوات في الطب التكميلي وتراكيب المستخلصات الطبيعية"
        ],
        summaryAr: "طبيب أعشاب ومختص في الطب النباتي والكيمياء الحيوية وصناعة التراكيب الطبيعية. خلفية أكاديمية قوية في الكيمياء والأحياء مكنته من ابتكار حلول علاجية عشبية للحالات المستعصية."
    },
    {
        id: "raya-al-shiriani",
        nameAr: "ريا ناصر سعيد الشرياني",
        titleAr: "أستاذة",
        roleAr: "مدربة العلوم النفسية والتوجيه المهني",
        roleEn: "Psychological Sciences & Career Guidance Trainer",
        specializationAr: "مدرب العلوم النفسية والإرشاد السلوكي",
        specializationEn: "Psychological Sciences Trainer & Behavioral Counseling",
        category: "psychology",
        photo: "Albums/University_Assets/raya-alshariani.jpg",
        cvFile: "docs/faculty_cvs/cv_raya_alshariani.md",
        initials: "ر.ش",
        status: "معتمدة رسمياً",
        badgeType: "certified",
        location: "محافظة الداخلية، سلطنة عُمان",
        email: "new99420239@gmail.com",
        phone: "+96876950239",
        credentials: [
            "ماجستير في الإرشاد النفسي – جامعة نزوى (2011م)",
            "بكالوريوس تربية فنية – جامعة السلطان قابوس (1995م)",
            "دبلوم التوجيه المهني – المديرية العامة للتربية والتعليم (2015م)",
            "دورة المسارات العصبية للمعالجة والتأهيل النفسي – د. ريما مسلم",
            "خبرة تفوق 20 عاماً في مجالات التربية والإرشاد النفسي والتوجيه المهني"
        ],
        summaryAr: "أخصائية توجيه مهني واستشارية إرشاد نفسي بسلطنة عُمان بخبرة تزيد عن 20 عاماً. متخصصة في توظيف علم المسارات العصبية والتغذية العلاجية في التوازن والاستقرار النفسي."
    },
    {
        id: "abdulwahed-jamil",
        nameAr: "عبد الواحد عبد الله عبد الوهاب جميل",
        titleAr: "أستاذ",
        roleAr: "متخصص في علم عقاقير الأعشاب والطب النبوي",
        roleEn: "Herbal Pharmacognosy & Prophetic Medicine Specialist",
        specializationAr: "علم عقاقير الأعشاب والعلاج النباتي",
        specializationEn: "Herbal Pharmacognosy & Phytotherapy",
        category: "herbal",
        photo: "Albums/University_Assets/abdulwahed-jamil.jpg",
        cvFile: "docs/faculty_cvs/cv_abdallah_jameel.md",
        initials: "ع.ج",
        status: "معتمد رسمياً",
        badgeType: "certified",
        location: "اليمن",
        credentials: [
            "بكالوريوس دراسات إسلامية (2017م)",
            "دبلوم العلاج النباتي ودبلوم الطب النبوي – د. مصطفى الصوفي",
            "دبلوم الصيدلة التحليلية ودبلوم طب الأعشاب والتغذية",
            "دبلوم التغذية العلاجية الصحية ودبلوم المدرب المحترف (TOT)",
            "باحث ماجستير في التنمية البشرية – مؤسسة الفقهية العالمية",
            "عضو رابطة المسندين اليمنيين وملتقى رقاة اليمن"
        ],
        summaryAr: "متخصص في علم عقاقير الأعشاب والطب النبوي والتغذية العلاجية. يمتلك إجازات علمية مسندة في العلوم الشرعية والطب التراثي، وإمام وخطيب ومدير مراكز قرآنية."
    },
    {
        id: "obeida-alshamiya",
        nameAr: "عبيدة محمد الشامية",
        titleAr: "أستاذة",
        roleAr: "أخصائية علاج بالحجامة والعلق الطبي ومنتجات النحل",
        roleEn: "Cupping, Hirudotherapy & Apitherapy Specialist",
        specializationAr: "التأهيل الحركي الوظيفي والحجامة الشمولية والعلق الطبي",
        specializationEn: "Functional Movement Rehabilitation, Cupping & Apitherapy",
        category: "rehab",
        photo: "Albums/University_Assets/obeida-alshamiya.jpg",
        cvFile: "docs/faculty_cvs/cv_obaida_alshameya.md",
        initials: "ع.ش",
        status: "معتمدة رسمياً",
        badgeType: "certified",
        location: "ريف دمشق، سوريا",
        phone: "+963918834686",
        credentials: [
            "بكالوريوس شريعة إسلامية – جامعة أم درمان (2006م)",
            "دبلوم العلاج بالحجامة – الاتحاد العالمي IUCM فرنسا والرابطة السورية (2024م)",
            "دبلوم العلاج بمنتجات النحل – الاتحاد العالمي IUCM فرنسا (2024م)",
            "شهادة تدريب المدربين الدولية (T.O.T) – مركز رؤى (2024م)",
            "خبرة تطبيقية في الحجامة منذ 2007م والعلاج بالعلق الطبي منذ 2022م"
        ],
        summaryAr: "أخصائية علاج بالحجامة الطبية الشمولية والعلق الطبي والمنتجات الطبيعية للنحل وسمّه. تمتلك خبرة ميدانية تتجاوز 17 عاماً في تطبيقات المساج العلاجي والتأهيلي والاسترخائي."
    },
    {
        id: "dr-hallouma-sekkak",
        nameAr: "د. حلومة سكاك",
        titleAr: "دكتورة",
        roleAr: "أستاذة وباحثة في علم الأعشاب المهنية",
        roleEn: "Professional Herbal Science Specialist & Researcher",
        specializationAr: "علم الأعشاب المهنية والطب الطبيعي",
        specializationEn: "Professional Herbal Science & Natural Medicine",
        category: "herbal",
        photo: null,
        cvFile: null,
        initials: "ح.س",
        status: "معتمدة رسمياً",
        badgeType: "certified",
        location: "الجزائر",
        credentials: [
            "دكتوراه وباحثة في علوم الأعشاب الطبية وتطبيقاتها",
            "شهادات تخصصية في إعداد الخلاصات الطبيعية",
            "عضو الهيئة الأكاديمية والتدريسية في الجامعة العالمية الافتراضية"
        ],
        summaryAr: "عضو الهيئة التدريسية المعتمدة بالجامعة ومتخصصة في علم الأعشاب المهنية وأبحاث التداوي بالنباتات الطبية والطب الطبيعي."
    },
    {
        id: "asmaa-al-hallaq",
        nameAr: "أسماء الحلاق",
        titleAr: "أستاذة",
        roleAr: "أستاذة وباحثة في علم الأعشاب والطب التكميلي",
        roleEn: "Professional Herbal Science Specialist",
        specializationAr: "علم الأعشاب المهنية والطب التكميلي",
        specializationEn: "Professional Herbal Science & Complementary Care",
        category: "herbal",
        photo: "Albums/University_Assets/asmaa-al-hallaq.jpg",
        cvFile: null,
        initials: "أ.ح",
        status: "معتمدة رسمياً",
        badgeType: "certified",
        location: "سوريا",
        credentials: [
            "متخصصة وباحثة في علوم الأعشاب المهنية والطب التكميلي",
            "شهادات معتمدة في العلاج الطبيعي والتغذية التكميلية",
            "عضو الهيئة الأكاديمية والتدريسية في الجامعة العالمية الافتراضية"
        ],
        summaryAr: "عضو الهيئة التدريسية المعتمدة بالجامعة ومتخصصة في علوم الأعشاب المهنية والبرامج التدريبية المعتمدة في الطب الشمولي والتكميلي."
    }
];
